name: Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test-make:
    name: Test Make Recipes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continue with other versions if one fails
      matrix:
        versions:
          - python: "3.8"
          - python: "3.9"
          - python: "3.10"
          - python: "3.11"
          - python: "3.12"
          - python: "3.13"	  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for version commands
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.versions.python }}

      - name: Setup
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          make setup

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc
          version: '3.3'

      # Info commands
      - run: make
      - run: make help
      - run: make info
      - run: make info-long
      - run: make version

      # Dependency commands  
      - run: make dep-check
      - run: make dep
      - run: make dep-check-torch

      # Code quality commands
      - run: make format-check
      - run: make format 
      - run: make typing

      # Build commands
      - run: make build
      - run: make verify-git

      # Testing commands
      - run: make test
      - run: make check
      - run: make cov

      # Documentation commands
      - run: make docs-html
      - run: make docs-md
      - run: make docs-combined
      - run: make docs
      - run: make todo
      - run: make lmcat
      - run: make lmcat-tree

      # Cleanup commands  
      - run: make docs-clean
      - run: make clean
      - run: make dep-clean
      - run: make clean-all